version: '3.9'

services:
  db1:
    image: postgres:latest
    container_name: cafe-guider-api
    restart: always
    working_dir: /home
    environment:
      POSTGRES_PASSWORD: "1234567890"
    ports:
      - 3303:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/initdb.d:/docker-entrypoint-initdb.d
volumes:
  data:
    driver: local