version: '3.9'

services:
  db1:
    image: postgres:latest
    container_name: cafe-guider-db
    restart: always
    working_dir: /home
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 3303:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/initdb.d:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "logging_collector=on"]
volumes:
  data:
    driver: local